- hosts: all
  become_method: su
  vars_files:
    - variables.yml
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{docker_user}}"
        state: present
        key: "{{ lookup('file', pub_key) }}"
    - name: Install sudo
      become: true
      apt:
        name: sudo
        cache_valid_time: 3600
    - name: "Add {{docker_user}} to sudoers"
      become: true
      user:
        name: "{{docker_user}}"
        groups: sudo
        append: yes
    - name: Enable ip forwarding
      become: true
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
    - name: Install prerequisites for Docker
      become: yes
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'rsync']
        cache_valid_time: 3600
    - name: Add Docker GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    - name: Add docker repository
      become: yes
      apt_repository:
        filename: docker
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable"
        state: present
    - name: Install docker engine
      become: yes
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        update_cache: yes
    - name: Install docker compose
      become: yes
      block:
        - name: "Get docker-compose"
          get_url:
              url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-{{ansible_system}}-{{ansible_machine}}
              dest: /usr/local/bin/docker-compose
        - name: "Allow docker-compose execution"
          file:
            path: /usr/local/bin/docker-compose
            mode: u+x
        - name: "Create docker-compose symlink"
          file:
            src: /usr/local/bin/docker-compose
            dest: /usr/bin/docker-compose
            state: link
